import { strToU8, zipSync } from 'fflate'
import type { ExportOutput, ExportResult, ForegroundTransform, LoadedAsset } from '../types'
import { canvasToBlob, renderIcon } from './images'

const OUTPUTS = [
  { size: 432, density: 'xxxhdpi' },
  { size: 324, density: 'xxhdpi' },
  { size: 216, density: 'xhdpi' },
  { size: 162, density: 'hdpi' },
  { size: 108, density: 'mdpi' },
  { size: 81, density: 'ldpi' },
]

type ExportOptions = {
  background: LoadedAsset | null
  foreground: LoadedAsset
  backgroundColor: string
  transform: ForegroundTransform
  projectName: string
  onProgress?: (progress: number, phase: string) => void
}

function sanitizeProjectName(value: string) {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-|-$/g, '')
  return normalized || 'app'
}

async function sha256(bytes: Uint8Array) {
  const buffer = await crypto.subtle.digest('SHA-256', bytes as BufferSource)
  return [...new Uint8Array(buffer)].map((value) => value.toString(16).padStart(2, '0')).join('')
}

async function renderLayer(
  size: number,
  layer: 'background' | 'foreground' | 'composite',
  options: ExportOptions,
) {
  const canvas = document.createElement('canvas')
  renderIcon(canvas, {
    size,
    background: options.background,
    foreground: options.foreground,
    backgroundColor: options.backgroundColor,
    transform: options.transform,
    layer,
  })
  const blob = await canvasToBlob(canvas)
  return new Uint8Array(await blob.arrayBuffer())
}

function buildReadme(projectName: string) {
  return `# ${projectName} adaptive icon export

Generated by Adaptive Icon Generator.

## Unity assignment

Open \`Project Settings → Player → Android → Icon → Adaptive\`.

For each Unity size slot, assign both files from the matching numbered folder:

| Unity size | Folder | Layers |
|---:|---|---|
| 432 × 432 | \`unity/adaptive/432/\` | Background.png + Foreground.png |
| 324 × 324 | \`unity/adaptive/324/\` | Background.png + Foreground.png |
| 216 × 216 | \`unity/adaptive/216/\` | Background.png + Foreground.png |
| 162 × 162 | \`unity/adaptive/162/\` | Background.png + Foreground.png |
| 108 × 108 | \`unity/adaptive/108/\` | Background.png + Foreground.png |
| 81 × 81 | \`unity/adaptive/81/\` | Background.png + Foreground.png |

The background files are opaque and full bleed. The foreground files retain transparent padding. Do not flatten the two layers before assigning them to Unity.
`
}

export async function generateUnityZip(options: ExportOptions): Promise<ExportResult> {
  const projectName = sanitizeProjectName(options.projectName)
  const entries: Record<string, Uint8Array> = {}
  const outputs: ExportOutput[] = []
  const totalRenders = OUTPUTS.length * 2 + 1
  let completed = 0

  options.onProgress?.(2, 'Validating')

  for (const output of OUTPUTS) {
    for (const layer of ['background', 'foreground'] as const) {
      const path = `unity/adaptive/${output.size}/${layer === 'background' ? 'Background.png' : 'Foreground.png'}`
      const bytes = await renderLayer(output.size, layer, options)
      entries[path] = bytes
      outputs.push({
        path,
        width: output.size,
        height: output.size,
        layerType: layer,
        density: output.density,
        sha256: await sha256(bytes),
        alphaExpected: layer === 'foreground',
      })
      completed += 1
      options.onProgress?.(Math.round((completed / totalRenders) * 78), `Rendering ${output.density}`)
      await new Promise((resolve) => window.setTimeout(resolve, 0))
    }
  }

  const preview = await renderLayer(512, 'composite', options)
  entries['source-preview.png'] = preview
  completed += 1
  options.onProgress?.(82, 'Writing manifest')

  const generatedAt = new Date().toISOString()
  const manifest = {
    schemaVersion: 1,
    preset: 'unity-android-adaptive',
    generatedAt,
    safeMode: options.transform.targetSize <= 60 ? 'auto-fit' : 'strict-maximum',
    logicalCanvas: 108,
    safeZone: 66,
    targetArtworkSize: options.transform.targetSize,
    foregroundOffset: { x: options.transform.offsetX, y: options.transform.offsetY },
    foregroundAlphaThreshold: 8,
    outputs,
  }
  entries['manifest.json'] = strToU8(JSON.stringify(manifest, null, 2))
  entries['README.md'] = strToU8(buildReadme(projectName))

  options.onProgress?.(88, 'Packaging ZIP')
  await new Promise((resolve) => window.setTimeout(resolve, 0))
  const zipped = zipSync(entries, { level: 6 })
  const blob = new Blob([zipped as BlobPart], { type: 'application/zip' })
  const date = generatedAt.slice(0, 10)
  options.onProgress?.(100, 'Ready')

  return {
    fileName: `${projectName}-adaptive-icons-${date}.zip`,
    url: URL.createObjectURL(blob),
    byteLength: blob.size,
    outputCount: outputs.length,
    generatedAt,
  }
}
